<?php
/**
 * ACF helper functions
 */

// change / add to the base background choices here
$base_background_options = array (
	'no-background' 		=> 'No background',
	'inverse-background' 	=> 'Inverse',
	'primary-background'	=> 'Primary color background',
);

// grab any accent colors added in the site options with ACF
$acf_color_options = array();
if( get_option( 'options_accent_colors_container_accent_color_array' ) ) :
	$number = get_option( 'options_accent_colors_container_accent_color_array' );
	for ( $i=1; $i<=(int)$number; $i++ ) {
		$acf_color_options[ 'accent-color-' . $i ] = "Accent color #" . $i;
	}
endif;

// now merge those two arrays for all the background options
$background_choices_available = array_merge( $base_background_options, $acf_color_options );


// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'page',
		),
	),
/*	add any additional post types here. 
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
*/
);


//***************************************   SITE OPTIONS
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array (
	'key' => 'group_57f7c88c9aa18',
	'title' => 'Site Options',
	'fields' => array (
		array (
			'key' => 'field_57fbf3676e7e9',
			'label' => 'Display Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a1f1b703a28e',
			'label' => 'Site Logo',
			'name' => 'site_logo',
			'type' => 'image',
			'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, gif, svg, png',
		),
		array (
			'key' => 'field_57f7c92167a96',
			'label' => 'Default Featured Image',
			'name' => 'default_post_thumbnail_id',
			'type' => 'image',
			'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57fc43235c0d0',
			'label' => 'Excerpt Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_57fbf44a6e7f0',
			'label' => 'Length',
			'name' => 'excerpt_length',
			'type' => 'number',
			'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 40,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57fbf4686e7f1',
			'label' => 'Units',
			'name' => 'excerpt_length_unit',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'words' => 'Words',
				'chars' => 'Characters',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'words',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57fc42c5a2686',
			'label' => 'Link Text',
			'name' => 'excerpt_link_text',
			'type' => 'text',
			'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read more',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a1dd45d5edcf',
			'label' => 'Disable page sections on regular pages',
			'name' => 'disable_sections_on_pages',
			'type' => 'true_false',
			'instructions' => 'Check this box to remove the "page sections" editing capabilities on all inside pages of the site. The sections capabilities will then only show up on the front homepage (if a static page is used for the front page) and all inside pages will use the default WordPress page editor.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'message' => 'Use the default WordPress page editor',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5a1d8a764a977',
			'label' => 'Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5a1d8a994a978',
			'label' => 'Base colors',
			'name' => 'base_colors',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d8aae4a979',
					'label' => 'Background color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d8b844a97a',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565050',
				),
				array(
					'key' => 'field_5a1d8b944a97b',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#6D7298',
				),
				array(
					'key' => 'field_5a1d8bf64a97c',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565FA3',
				),
			),
		),
		array (
			'key' => 'field_5a1d8e351faec',
			'label' => 'Primary colors',
			'name' => 'primary_colors',
			'type' => 'group',
			'instructions' => 'For use of your main brand color. Text and link colors refer to the text/links on top of the primary brand color',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d8e351faed',
					'label' => 'Primary color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FE5F55',
				),
				array(
					'key' => 'field_5a1d8e351faee',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d8e351faef',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FCE197',
				),
				array(
					'key' => 'field_5a1d8e351faf0',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array (
			'key' => 'field_5a1d90238a9b7',
			'label' => 'Inverse colors',
			'name' => 'inverse_colors',
			'type' => 'group',
			'instructions' => 'For an "inverse" option of the main/base colors.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d90238a9b8',
					'label' => 'Background color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565050',
				),
				array(
					'key' => 'field_5a1d90238a9b9',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d90238a9ba',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#B9D8F7',
				),
				array(
					'key' => 'field_5a1d90238a9bb',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array (
			'key' => 'field_5a1d914942cc6',
			'label' => 'Accent colors',
			'name' => 'accent_colors_container',
			'type' => 'group',
			'instructions' => 'Add any additional accent colors',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d91aa42cc7',
					'label' => 'All accent colors',
					'name' => 'accent_color_array',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5a1d91f142cc9',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add a color',
					'sub_fields' => array(
						array(
							'key' => 'field_5a1d91f142cc9',
							'label' => 'Accent color',
							'name' => 'accent_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#ffffff',
						),
						array(
							'key' => 'field_5a1d91f142cc8',
							'label' => 'Text',
							'name' => 'accent_color_details',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5a1d91f142cca',
									'label' => 'Text color',
									'name' => 'text_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#565050',
								),
								array(
									'key' => 'field_5a1d91f142ccb',
									'label' => 'Link color',
									'name' => 'link_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#6D7298',
								),
								array(
									'key' => 'field_5a1d91f142ccc',
									'label' => 'Link hover',
									'name' => 'link_hover',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#565FA3',
								),
							),
						),
					),
				),
			),
		),
		array (
			'key' => 'field_57fbf37a6e7ea',
			'label' => 'Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ceae82de8',
			'label' => 'Contact Info',
			'name' => 'contact_info',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_57fbf4cf6e7f2',
			'label' => 'Copyright Text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © [year]. All rights reserved.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57fbf39a6e7eb',
			'label' => 'URLs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ca2067a98',
			'label' => 'Social Media Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57f7ca3567a99',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Service',
			'sub_fields' => array (
				array (
					'key' => 'field_57f7ca3567a99',
					'label' => 'Service',
					'name' => 'service',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'flickr' => 'Flickr',
						'googleplus' => 'Google+',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'pinterest' => 'Pinterest',
						'snapchat' => 'Snapchat',
						'tumblr' => 'Tumblr',
						'twitter' => 'Twitter',
						'youtube' => 'YouTube',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_57f7cb1267a9b',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57f7caee67a9a',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_57fbf3ab6e7ec',
			'label' => 'Integrations/API Keys',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7d17269b71',
			'label' => 'Facebook App ID',
			'name' => 'facebook_app_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57f7ca0467a97',
			'label' => 'Google Maps API Key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'start-site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'modified' => 1476826847,
));


endif;

